// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sampaio.Data;

#nullable disable

namespace Sampaio.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sampaio.Domain.Entities.BackofficeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.HasKey("Id");

                    b.ToTable("BackofficeUsers", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CommerceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.HasIndex("CommerceId");

                    b.HasIndex("DriverId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CartId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<Guid?>("ProductId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(Max)")
                        .HasColumnName("Name");

                    b.Property<string>("StateId")
                        .HasColumnType("Varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Commerce", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<bool?>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool?>("Homologated")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(5000)");

                    b.Property<Guid?>("SegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.ToTable("Commerces", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.CommerceSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CommerceSegments", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<Guid?>("DriverId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QrCode")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("QrCodeImage")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PlanId");

                    b.ToTable("Debts", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.DebtPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid?>("DebtId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.ToTable("DebtPayments", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime");

                    b.Property<string>("CnhNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PlanStartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Exception")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Logger")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("OccurredAt");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Passageiro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Assento")
                        .HasColumnType("int");

                    b.Property<bool>("Comprador")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ViagemPagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.HasIndex("ViagemPagamentoId");

                    b.ToTable("Passageiros", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("DebtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DebtId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("MonthValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CommerceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Discount");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("OriginalPrice");

                    b.Property<Guid?>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CommerceId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductsCategories", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid?>("CommerceId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid?>("DriverId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("SalePrice");

                    b.HasKey("Id");

                    b.HasIndex("CommerceId");

                    b.HasIndex("DriverId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<decimal>("ProductDiscountPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ProductDiscountPrice");

                    b.Property<Guid?>("ProductId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ProductName");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ProductPrice");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("SaleId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.State", b =>
                {
                    b.Property<string>("Initials")
                        .HasColumnType("Varchar(2)")
                        .HasColumnName("Initials");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Initials");

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Active");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("PasswordRecoverToken")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.UserPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPhones", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("datetime");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QtdVagas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Viagens", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.ViagemPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("IdTransacao")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PagamentoStatus")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PixQrCode")
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("QuantidadePassagens")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.ToTable("ViagemPagamentos", (string)null);
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.BackofficeUser", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.User", "User")
                        .WithOne("BackofficeUser")
                        .HasForeignKey("Sampaio.Domain.Entities.BackofficeUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Commerce", "Commerce")
                        .WithMany("Carts")
                        .HasForeignKey("CommerceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Sampaio.Domain.Entities.Driver", "Driver")
                        .WithMany("Carts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Commerce");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sampaio.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.City", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("State");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Commerce", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.User", "User")
                        .WithOne("Commerce")
                        .HasForeignKey("Sampaio.Domain.Entities.Commerce", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sampaio.Domain.Entities.CommerceSegment", "Segment")
                        .WithMany("Commerces")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("Sampaio.Shared.ValueObjects.Identification", "Identification", b1 =>
                        {
                            b1.Property<Guid>("CommerceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Identification_Number");

                            b1.Property<string>("Type")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Identification_Type");

                            b1.HasKey("CommerceId");

                            b1.ToTable("Commerces");

                            b1.WithOwner()
                                .HasForeignKey("CommerceId");
                        });

                    b.OwnsOne("Sampaio.Domain.ValueObjects.AddressInformation", "AddressInformation", b1 =>
                        {
                            b1.Property<Guid>("CommerceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasColumnType("varchar(255)")
                                .HasColumnName("AddressInformation_Address");

                            b1.Property<Guid>("CityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Complement")
                                .HasColumnType("varchar(max)")
                                .HasColumnName("AddressInformation_Complement");

                            b1.Property<string>("Neighborhood")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("AddressInformation_Neighborhood");

                            b1.Property<string>("Number")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("AddressInformation_Number");

                            b1.Property<string>("StateId")
                                .HasColumnType("Varchar(2)");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("AddressInformation_ZipCode");

                            b1.HasKey("CommerceId");

                            b1.HasIndex("CityId");

                            b1.HasIndex("StateId");

                            b1.ToTable("Commerces");

                            b1.HasOne("Sampaio.Domain.Entities.City", "City")
                                .WithMany()
                                .HasForeignKey("CityId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("CommerceId");

                            b1.HasOne("Sampaio.Domain.Entities.State", "State")
                                .WithMany()
                                .HasForeignKey("StateId")
                                .OnDelete(DeleteBehavior.NoAction);

                            b1.Navigation("City");

                            b1.Navigation("State");
                        });

                    b.Navigation("AddressInformation");

                    b.Navigation("Identification");

                    b.Navigation("Segment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Debt", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Driver", "Driver")
                        .WithMany("Debts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sampaio.Domain.Entities.Plan", "Plan")
                        .WithMany("Debts")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Driver");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.DebtPayment", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Debt", "Debt")
                        .WithMany("DebtPayments")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Debt");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Driver", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("Sampaio.Domain.Entities.Driver", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sampaio.Domain.Entities.Plan", "Plan")
                        .WithMany("Drivers")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("Sampaio.Shared.ValueObjects.Identification", "Identification", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Identification_Number");

                            b1.Property<string>("Type")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Identification_Type");

                            b1.HasKey("DriverId");

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("Identification");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Passageiro", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Viagem", "Viagem")
                        .WithMany("Passageiros")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sampaio.Domain.Entities.ViagemPagamento", "Pagamento")
                        .WithMany("Passageiros")
                        .HasForeignKey("ViagemPagamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Pagamento");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Debt", "Debt")
                        .WithMany("Payments")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Debt");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Product", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Commerce", "Commerce")
                        .WithMany("Products")
                        .HasForeignKey("CommerceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sampaio.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Commerce");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Commerce", "Commerce")
                        .WithMany("Sales")
                        .HasForeignKey("CommerceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sampaio.Domain.Entities.Driver", "Driver")
                        .WithMany("Sales")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Commerce");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Sampaio.Domain.Entities.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.UserPhone", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.User", "User")
                        .WithMany("Phones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Sampaio.Shared.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("UserPhoneId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Number")
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Number");

                            b1.Property<string>("Type")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Type");

                            b1.HasKey("UserPhoneId");

                            b1.ToTable("UserPhones");

                            b1.WithOwner()
                                .HasForeignKey("UserPhoneId");
                        });

                    b.Navigation("Phone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.ViagemPagamento", b =>
                {
                    b.HasOne("Sampaio.Domain.Entities.Viagem", "Viagem")
                        .WithMany("ViagemPagamentos")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Commerce", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Products");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.CommerceSegment", b =>
                {
                    b.Navigation("Commerces");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Debt", b =>
                {
                    b.Navigation("DebtPayments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Debts");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Debts");

                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.User", b =>
                {
                    b.Navigation("BackofficeUser");

                    b.Navigation("Commerce");

                    b.Navigation("Driver");

                    b.Navigation("Phones");

                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.Viagem", b =>
                {
                    b.Navigation("Passageiros");

                    b.Navigation("ViagemPagamentos");
                });

            modelBuilder.Entity("Sampaio.Domain.Entities.ViagemPagamento", b =>
                {
                    b.Navigation("Passageiros");
                });
#pragma warning restore 612, 618
        }
    }
}
